# Generated by Django 5.2.4 on 2025-07-20 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pereval',
            name='connect',
            field=models.CharField(blank=True, null=True),
        ),
    ]
